from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def create_pdf(filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    for i in range(1, 11):
        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawString(1 * inch, 10.5 * inch, f"Homelab AI Project - Page {i}")
        
        # Decorative Line
        c.line(1 * inch, 10.3 * inch, 7.5 * inch, 10.3 * inch)

        # Body Text
        c.setFont("Helvetica", 12)
        text_object = c.beginText(1 * inch, 9.5 * inch)
        
        lines = [
            f"This is page {i} of your generated document.",
            "",
            "Project Directory: ~/homelab-ai/backend/services/",
            "Status: System Functional",
            "Objective: Automating AI workloads in a local environment.",
            "",
            "Sample Log Data:",
            f" - Initialization of module_{i} complete.",
            f" - Heartbeat detected on port 808{i}.",
            " - Security handshake: SUCCESS.",
            "",
            "Placeholder content for layout testing:"
        ]
        
        # Add some filler text to make it look like a real document
        filler = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " * 10
        lines.append(filler)

        for line in lines:
            text_object.textLine(line)
        
        c.drawText(text_object)

        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(1 * inch, 0.75 * inch, f"Generated by AI Assistant | Page {i}")

        # Finalize the page and start a new one
        c.showPage()

    c.save()
    print(f"Successfully created {filename}")

if __name__ == "__main__":
    create_pdf("homelab_doc.pdf")
